version: 2.1

orbs:
  nx: nrwl/nx@1.6.2

jobs:
  checks:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pnpm install --frozen-lockfile
      - nx/set-shas
      - run:
          name: Run Builds
          command: nx affected --target=build --base=$NX_BASE --parallel
      - run:
          name: Run Unit Tests
          command: nx affected --target=test --base=$NX_BASE --parallel
